DROP TABLE IF EXISTS kunde CASCADE;

CREATE TABLE IF NOT EXISTS kunde(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    kontakt TEXT,
    email TEXT,
    telefon TEXT,
    erstellt_am TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
